#! /bin/sh -f
#\
mkdir -p logfiles
#\
mkdir -p patterns
#\
exec tessent -shell -log logfiles/$0.log -replace -dofile "$0"

set PDK_ROOT ../../../tech

set_context pattern -scan

set_tsdb_output_directory ../tsdb_outdir


read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_stdcell.tcelllib
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_io.tcelllib

## Reads in the scan inserted netlist/design
read_design NV_NVDLA_partition_c  -design_id gate3 -verbose

#read_cell_library ${PDK_ROOT}/tessent/memories/RM_IHPSG13_1P_256x64_c2_bm_bist.atpglib

#
#not reading Icl since constraints ijtag signals automatically
set_current_design NV_NVDLA_partition_c



add_black_boxes -modules {\
                        RAMPDP_256X64_GL_M2_D2 \
                        RAMDP_16X64_GL_M1_E2 \
                        RAMDP_8X66_GL_M1_E2 \
                        RAMDP_128X6_GL_M2_E2 \
                        RAMDP_128X11_GL_M2_E2 \
                        } 
                        
set_current_mode ccm_atpg


# dont import scan mode when  not reading design (no tcd)
import_scan_mode controller_chain_mode

set_system_mode analysis

add_faults [get_instance {*tessent_lbist_inst *tessent*single* *edt_lbist*}]

create_patterns -cov high

write_tsdb_data -replace
write_patterns patterns/NV_NVDLA_partition_a_ccm_stuck_parallel.v -verilog -parallel -replace -parameter_list {SIM_KEEP_PATH 1}
write_patterns patterns/NV_NVDLA_partition_a_ccm_stuck_serial.v -verilog -serial -replace -parameter_list {SIM_KEEP_PATH 1}

# In order to account the coverage of the faults testable by Internal modes (bypass on/off) 
read_faults -mode edt_int_stuck -fault_type stuck -merge
read_faults -fault_type stuck -mode ext_multi_stuck -merge 
read_faults -fault_type stuck -mode lbist_sa -merge 
read_faults -fault_type stuck -mode ccm_atpg -merge 
delete_faults -class AU.BB 

report_statistics -detail
exit
