#! /bin/sh -f
#\
mkdir -p logfiles
#\
mkdir -p patterns
#\
exec tessent -shell -log logfiles/$0.log -replace -dofile "$0"
proc cleanup { {pathname_list ""}  } { 
  file delete -force  simulation_outdir  ;
  file delete -force  synthesis_outdir ;
  file delete -force  patterns/* ;
  foreach pathname $pathname_list { file delete -force $pathname  ; } ;
 } 

 cleanup ;

set PDK_ROOT ../../../tech

# Specify the context to pattern -ijtag to generate LBIST pattern
set_context patterns -ijtag 

# Specify where the tsdb_outdir is to be located, default is at the current working directory
set_tsdb_output_directory ../tsdb_outdir

# Read Tessent Library
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_stdcell.tcelllib
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_io.tcelllib

# Read in the scan inserted netlist/design
read_design NV_NVDLA_partition_o  -design_id gate3

##Read in the memory library model
#read_cell_library ${PDK_ROOT}/tessent/memories/RM_IHPSG13_1P_256x64_c2_bm_bist.atpglib

#set_design_sources -format tcd_memory -Y ${PDK_ROOT}/tessent/memories -extension tcd_memory


set_current_design NV_NVDLA_partition_o 

report_black_boxes -undefined
add_black_boxes -modules {\
                        RAMDP_256X4_GL_M2_E2 \
                        RAMDP_256X8_GL_M2_E2 \
                        RAMPDP_128X18_GL_M2_D2 \
                        RAMDP_8X66_GL_M1_E2 \
                        RAMDP_80X9_GL_M2_E2 \
                        RAMPDP_80X17_GL_M2_D2 \
                        RAMDP_60X22_GL_M1_E2 \
                        }

add_input_constraints direct_reset_ -C1
add_input_constraints dla_reset_rstn -C1
# Report clock and dft signal settings
#set_static_dft_signal_value force_testmode_i_zero 0
add_clocks 0 nvdla_core_clk -period 10ns
add_clocks 0 nvdla_falcon_clk -period 20ns

report_static_dft_signal_settings
report_clocks

set_system_mode analysis
set_split_capture_cycle on 

#specify pattern spec settings
set patt_spec [ create_patterns_specification  ]
 report_config_data

read_config_data -replace -in $patt_spec -from_string {
  AdvancedOptions {
    ConstantPortSettings {
      scan_enable : 0;
    }
  }
  Patterns(ICLNetwork) {
    ICLNetworkVerify(NV_NVDLA_partition_o) {
    }
  }
  Patterns(LogicBist_NV_NVDLA_partition_o) {
    ClockPeriods {
      nvdla_core_clk : 10.00ns;
      nvdla_falcon_clk : 20.00ns;
      test_clock: 40.00ns;
    }
   SimulationOptions {
        logic_bist_debug : bist_registers_and_clock_verify;
      }
   TestStep(serial_load) {
      LogicBist {
        CoreInstance(.) {
          run_mode : run_time_prog;
          mode_name : lbist_sa ;//same as set_current_mode in lbist fault simulation 
          warmup_pattern_count : 4;
          begin_pattern : 0;
          end_pattern : 7 ;
		      misr_compares : 1 ;
          // DiagnosisOptions {
          //  extract_flop_data : on ;
          // }
        }
      }
    }
  }
}
 
process_pattern_specification
## Run Simulations
#set_simulation_library_sources -y ../../../library/memories/ -extension v -v ../../../library/standard_cells/verilog/adk.v 
set_simulation_library_sources -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_stdcell/verilog/sg13g2_stdcell.v \
                              -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_io/verilog/sg13g2_io.v \
                              -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_sram/verilog/*.v \
                              -v ../../nv_small/outdir/nv_small/vmod/rams/model/RAMDP_256X4_GL_M2_E2.v \
                              -v ../../nv_small/outdir/nv_small/vmod/rams/model/RAMDP_256X8_GL_M2_E2.v \
                              -v ../../nv_small/outdir/nv_small/vmod/rams/model/RAMPDP_128X18_GL_M2_D2.v \
                              -v ../../nv_small/outdir/nv_small/vmod/rams/model/RAMDP_8X66_GL_M1_E2.v \
                              -v ../../nv_small/outdir/nv_small/vmod/rams/model/RAMDP_80X9_GL_M2_E2.v \
                              -v ../../nv_small/outdir/nv_small/vmod/rams/model/RAMPDP_80X17_GL_M2_D2.v \
                              -v ../../nv_small/outdir/nv_small/vmod/rams/model/RAMDP_60X22_GL_M1_E2.v 
                              
                              #run_testbench_simulations -simulator_option { -voptargs="+acc" }
run_testbench_simulations -simulator_option { -voptargs="+acc" } -compilation_options {verilog {+define+TETRAMAX +define+SYNTHESIS}}

# If simulation fails use the command below to see which pattern failed
check_testbench_simulations -report_status

exit

