/*
 *    DESC: Generated by Tessent FastScan at Thu Nov 13 12:08:45 EST 2025
 */
module MGC_DFT_LIB_ALL ( sg13g2_IOPadAnalog__pad , sg13g2_IOPadAnalog__padres , 
                         sg13g2_IOPadIn__pad , sg13g2_IOPadIn__p2c , 
                         sg13g2_IOPadInOut16mA__pad , sg13g2_IOPadInOut16mA__c2p , 
                         sg13g2_IOPadInOut16mA__c2p_en , 
                         sg13g2_IOPadInOut16mA__p2c , sg13g2_IOPadInOut30mA__pad , 
                         sg13g2_IOPadInOut30mA__c2p , 
                         sg13g2_IOPadInOut30mA__c2p_en , 
                         sg13g2_IOPadInOut30mA__p2c , sg13g2_IOPadInOut4mA__pad , 
                         sg13g2_IOPadInOut4mA__c2p , 
                         sg13g2_IOPadInOut4mA__c2p_en , 
                         sg13g2_IOPadInOut4mA__p2c , sg13g2_IOPadOut16mA__pad , 
                         sg13g2_IOPadOut16mA__c2p , sg13g2_IOPadOut30mA__pad , 
                         sg13g2_IOPadOut30mA__c2p , sg13g2_IOPadOut4mA__pad , 
                         sg13g2_IOPadOut4mA__c2p , sg13g2_IOPadTriOut16mA__pad , 
                         sg13g2_IOPadTriOut16mA__c2p , 
                         sg13g2_IOPadTriOut16mA__c2p_en , 
                         sg13g2_IOPadTriOut30mA__pad , 
                         sg13g2_IOPadTriOut30mA__c2p , 
                         sg13g2_IOPadTriOut30mA__c2p_en , 
                         sg13g2_IOPadTriOut4mA__pad , sg13g2_IOPadTriOut4mA__c2p , 
                         sg13g2_IOPadTriOut4mA__c2p_en );
input   sg13g2_IOPadInOut16mA__c2p , sg13g2_IOPadInOut16mA__c2p_en , 
        sg13g2_IOPadInOut30mA__c2p , sg13g2_IOPadInOut30mA__c2p_en , 
        sg13g2_IOPadInOut4mA__c2p , sg13g2_IOPadInOut4mA__c2p_en , 
        sg13g2_IOPadOut16mA__c2p , sg13g2_IOPadOut30mA__c2p , 
        sg13g2_IOPadOut4mA__c2p , sg13g2_IOPadTriOut16mA__c2p , 
        sg13g2_IOPadTriOut16mA__c2p_en , sg13g2_IOPadTriOut30mA__c2p , 
        sg13g2_IOPadTriOut30mA__c2p_en , sg13g2_IOPadTriOut4mA__c2p , 
        sg13g2_IOPadTriOut4mA__c2p_en ;
output  sg13g2_IOPadIn__p2c , sg13g2_IOPadInOut16mA__p2c , 
        sg13g2_IOPadInOut30mA__p2c , sg13g2_IOPadInOut4mA__p2c ;
inout  sg13g2_IOPadAnalog__pad , sg13g2_IOPadAnalog__padres , 
       sg13g2_IOPadIn__pad , sg13g2_IOPadInOut16mA__pad , 
       sg13g2_IOPadInOut30mA__pad , sg13g2_IOPadInOut4mA__pad , 
       sg13g2_IOPadOut16mA__pad , sg13g2_IOPadOut30mA__pad , 
       sg13g2_IOPadOut4mA__pad , sg13g2_IOPadTriOut16mA__pad , 
       sg13g2_IOPadTriOut30mA__pad , sg13g2_IOPadTriOut4mA__pad ;

  sg13g2_Corner  sg13g2_Corner ();
  sg13g2_Filler1000  sg13g2_Filler1000 ();
  sg13g2_Filler10000  sg13g2_Filler10000 ();
  sg13g2_Filler200  sg13g2_Filler200 ();
  sg13g2_Filler2000  sg13g2_Filler2000 ();
  sg13g2_Filler400  sg13g2_Filler400 ();
  sg13g2_Filler4000  sg13g2_Filler4000 ();
  sg13g2_IOPadAnalog  sg13g2_IOPadAnalog (sg13g2_IOPadAnalog__pad , 
                    sg13g2_IOPadAnalog__padres);
  sg13g2_IOPadIOVdd  sg13g2_IOPadIOVdd ();
  sg13g2_IOPadIOVss  sg13g2_IOPadIOVss ();
  sg13g2_IOPadIn  sg13g2_IOPadIn (sg13g2_IOPadIn__pad , sg13g2_IOPadIn__p2c);
  sg13g2_IOPadInOut16mA  sg13g2_IOPadInOut16mA (sg13g2_IOPadInOut16mA__pad , 
                       sg13g2_IOPadInOut16mA__c2p , 
                       sg13g2_IOPadInOut16mA__c2p_en , 
                       sg13g2_IOPadInOut16mA__p2c);
  sg13g2_IOPadInOut30mA  sg13g2_IOPadInOut30mA (sg13g2_IOPadInOut30mA__pad , 
                       sg13g2_IOPadInOut30mA__c2p , 
                       sg13g2_IOPadInOut30mA__c2p_en , 
                       sg13g2_IOPadInOut30mA__p2c);
  sg13g2_IOPadInOut4mA  sg13g2_IOPadInOut4mA (sg13g2_IOPadInOut4mA__pad , 
                      sg13g2_IOPadInOut4mA__c2p , sg13g2_IOPadInOut4mA__c2p_en , 
                      sg13g2_IOPadInOut4mA__p2c);
  sg13g2_IOPadOut16mA  sg13g2_IOPadOut16mA (sg13g2_IOPadOut16mA__pad , 
                     sg13g2_IOPadOut16mA__c2p);
  sg13g2_IOPadOut30mA  sg13g2_IOPadOut30mA (sg13g2_IOPadOut30mA__pad , 
                     sg13g2_IOPadOut30mA__c2p);
  sg13g2_IOPadOut4mA  sg13g2_IOPadOut4mA (sg13g2_IOPadOut4mA__pad , 
                    sg13g2_IOPadOut4mA__c2p);
  sg13g2_IOPadTriOut16mA  sg13g2_IOPadTriOut16mA (sg13g2_IOPadTriOut16mA__pad , 
                        sg13g2_IOPadTriOut16mA__c2p , 
                        sg13g2_IOPadTriOut16mA__c2p_en);
  sg13g2_IOPadTriOut30mA  sg13g2_IOPadTriOut30mA (sg13g2_IOPadTriOut30mA__pad , 
                        sg13g2_IOPadTriOut30mA__c2p , 
                        sg13g2_IOPadTriOut30mA__c2p_en);
  sg13g2_IOPadTriOut4mA  sg13g2_IOPadTriOut4mA (sg13g2_IOPadTriOut4mA__pad , 
                       sg13g2_IOPadTriOut4mA__c2p , 
                       sg13g2_IOPadTriOut4mA__c2p_en);
  sg13g2_IOPadVdd  sg13g2_IOPadVdd ();
  sg13g2_IOPadVss  sg13g2_IOPadVss ();
endmodule

