#! /bin/sh -f
#\
mkdir -p logfiles; export PDK_ROOT_SYN="$(realpath "../../../tech/synopsys")"; echo $PDK_ROOT_SYN
#\
exec tessent -shell -log logfiles/$0.log -replace -dofile "$0"
proc cleanup { {pathname_list ""}  } { 
  file delete -force  simulation_outdir  ;
  file delete -force  synthesis_outdir ;
  foreach pathname $pathname_list { file delete -force $pathname  ; } ;
 } 

 cleanup ;

set PDK_ROOT ../../../tech

# Open the previous TSDB directories if it is not in the current working directory
set_tsdb_output_directory ../tsdb_outdir

##Setting context to dft and  we are inserting DFT into gate-level design
set_context dft -no_rtl -design_id gate2


# Read Tessent Library
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_stdcell.tcelllib
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_io.tcelllib

##Read in the memory library model
#set_design_sources -format tcd_memory -Y ${PDK_ROOT}/tessent/memories -extension tcd_memory

##Read in memory verilog model
#read_verilog ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_sram/verilog/RM_IHPSG13_1P_core_behavioral_bm_bist.v -exclude_from_file_dictionary -interface_only
#read_verilog ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_sram/verilog/RM_IHPSG13_1P_256x64_c2_bm_bist.v -exclude_from_file_dictionary -interface_only


# Read the design files from the RTL insertion pass
# Use the -no_hdl switch to skip reading the netlist as the synthesized netlist has already been read
read_design NV_NVDLA_partition_p -design_id gate1 

set_current_design NV_NVDLA_partition_p

report_black_boxes -undefined
add_black_boxes -modules {\
                        RAMDP_16X14_GL_M1_E2 \
                        RAMDP_16X16_GL_M1_E2 \
                        RAMDP_16X66_GL_M1_E2 \
                        RAMDP_8X66_GL_M1_E2 \
                        }

##Setting the design level as physical_block
set_design_level physical_block

set_dft_specification_requirements  -logic_test on
#add core instance sti sib which is going to use by NCP decoder to create cycle for mini occ
#add_core_instances -instances [get_instances *_tessent_sib_sti_inst]


###===================================================================================================
## Needed for any logic test

add_dft_signals ltest_en -create_with_tdr
add_dft_signals scan_en edt_update test_clock -source_node { scan_enable edt_update test_clock }
add_dft_signals edt_clock shift_capture_clock -create_from_other_signals

## Needed for HTKLB TP
add_dft_signals observe_test_point_en  control_test_point_en x_bounding_en mcp_bounding_en controller_chain_mode
##

##Needed for MBIST

# DFT Signal used for Scan Tested Instruments like memorybist
add_dft_signals tck_occ_en
# DFT Signal used to bypass memories or to run multi-load ATPG for memories
add_dft_signals memory_bypass_en

# DFT signal to enable observation scan technology for capturing per shift and capture
#add_dft_signals capture_per_cycle_static_en

set_dft_specification_requirement -logic_test on
add_dft_signals int_mode ext_mode int_ltest_en ext_ltest_en

#add_clocks 0 jtag_tck_i -period 10ns 
add_dft_control_points [get_nets */nvdla_core_clk_slcg_1/p_clkgate/qd] -dft_signal_source_name all_test
add_dft_control_points [get_nets */nvdla_core_clk_slcg_0/p_clkgate/qd] -dft_signal_source_name all_test
add_dft_control_points [get_nets */nvdla_core_clk_mgate/p_clkgate/qd] -dft_signal_source_name all_test
add_dft_control_points [get_nets */UJ_clk_jtag_Data_reg_r0/qd] -dft_signal_source_name all_test
add_dft_control_points [get_nets \u_NV_NVDLA_sdp/u_wdma/u_cmd/u_dfifo/nvdla_core_clk_mgated_enable ] -dft_signal_source_name all_test
add_dft_control_points [get_nets \u_NV_NVDLA_sdp/u_rdma/u_mrdma/u_eg/u_cmd/u_sfifo/nvdla_core_clk_mgated_enable ] -dft_signal_source_name all_test

#add_nonscan_instances \u_NV_NVDLA_sdp/u_wdma/u_cmd/u_dfifo/nvdla_core_clk_mgate/p_clkgate/qd_reg
#add_nonscan_instances \u_NV_NVDLA_sdp/u_rdma/u_mrdma/u_eg/u_cmd/u_sfifo/nvdla_core_clk_mgate/p_clkgate/qd_reg
add_nonscan_instances \u_NV_NVDLA_sdp/u_rdma/u_nrdma/u_lat_fifo/ram/r_nv_ram_rwsp_16x65/testInst_ram_access_lockup/Q_reg
add_nonscan_instances \u_NV_NVDLA_sdp/u_rdma/u_nrdma/u_cq/ram/r_nv_ram_rwsp_16x16/testInst_ram_access_lockup/Q_reg
add_nonscan_instances \u_NV_NVDLA_sdp/u_rdma/u_brdma/u_lat_fifo/ram/r_nv_ram_rwsp_16x65/testInst_ram_access_lockup/Q_reg
add_nonscan_instances \u_NV_NVDLA_sdp/u_rdma/u_brdma/u_cq/ram/r_nv_ram_rwsp_16x16/testInst_ram_access_lockup/Q_reg
add_nonscan_instances \u_NV_NVDLA_sdp/u_rdma/u_mrdma/u_eg/u_din/u_lat_fifo/ram/r_nv_ram_rwsp_8x65/testInst_ram_access_lockup/Q_reg
add_nonscan_instances \u_NV_NVDLA_sdp/u_rdma/u_mrdma/u_cq/ram/r_nv_ram_rwsp_16x14/testInst_ram_access_lockup/Q_reg

check_design_rules

set spec [create_dft_specification -sri_sib_list { occ edt lbist } ]

read_config_data -in $spec -from_string {
add_persistent_buffers_in_scan_resource_instruments : on;
use_rtl_synchronizer_cell : on;
}
# Use report_config_syntax DftSpecification/edt|occ to see full syntax
report_config_data $spec

read_config_data -in $spec -from_string {

  OCC {
    ijtag_host_interface : Sib(occ);
    static_clock_control : both;
    }
}

set id_clk_list [list \
nvdla_core_clk nvdla_core_clk\
]
foreach {id clk} $id_clk_list {
  set occ [add_config_element OCC/Controller($id) -in $spec]
  set_config_value clock_intercept_node -in $occ $clk
}



# create wrapper for Hybrid TKLBIST and LogicBIST controller
read_config_data -in $spec -from_string {
   EDT {
     ijtag_host_interface : Sib(edt);
       Controller (c1) {
        longest_chain_range : 100, 200 ;
        scan_chain_count : 120;
        input_channel_count : 1;
        output_channel_count : 1;
        LogicBistOptions { 
          misr_input_ratio : 1 ;
          ShiftPowerOptions {
            present : on ;
            default_operation : disabled ;
            SwitchingThresholdPercentage {
              min : 25 ;
           }
         }
       }
    }
  }
}

read_config_data -in $spec -from_string {
  LogicBist {
    ijtag_host_interface : Sib(lbist);
    Controller(1%ctrl_lbist) {
      burn_in : on ;
      pre_post_shift_dead_cycles : 8 ;
      SingleChainForDiagnosis {
        Present : on ;
      }  
      ControllerChain {
         present : on; 
         clock : tck;
      }
      Connections {
	      shift_clock_src:nvdla_core_clk;
      }
      ShiftCycles { max :3000 ; }   
      CaptureCycles { max : 7; }   
      PatternCount { max : 8192; }   
      WarmupPatternCount { max : 255; }   
    }
  
   NcpIndexDecoder{
      Ncp(ALL) {
        cycle(0): OCC(nvdla_core_clk);
      }
      Ncp(single_pulse) {
        cycle(0): OCC(nvdla_core_clk);
      }
      Ncp(double_pulse) {
        cycle(0): OCC(nvdla_core_clk);
        cycle(1): OCC(nvdla_core_clk);
      }
    }

   }
}



process_dft_specification
## The icl for the entire design gets created
extract_icl 
set_run_synthesis_options dc_shell -post_compilation_commands {"redirect -append Synth.report {report_qor -significant_digits 4}"}
run_synthesis
# write script for design compilation
write_design_import_script  for_dc_synthesis.tcl -replace

# Make patterns
create_pattern_specification
process_pattern_specification
## Run Simulations
set_simulation_library_sources -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_stdcell/verilog/sg13g2_stdcell.v \
                              -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_io/verilog/sg13g2_io.v \
                              -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_sram/verilog/*.v \
                              -v ../../nv_small/outdir/nv_small/vmod/rams/model/RAMDP_16X14_GL_M1_E2.v \
                              -v ../../nv_small/outdir/nv_small/vmod/rams/model/RAMDP_16X16_GL_M1_E2.v \
                              -v ../../nv_small/outdir/nv_small/vmod/rams/model/RAMDP_16X66_GL_M1_E2.v \
                              -v ../../nv_small/outdir/nv_small/vmod/rams/model/RAMDP_8X66_GL_M1_E2.v 

run_testbench_simulations -compilation_options {verilog {+define+SYNTHESIS}} -simulator_option +nowarnTSCALE
check_testbench_simulations -report_status


exit
