/*
 *    DESC: Generated by Tessent FastScan at Thu Nov 13 13:42:48 EST 2025
 */
module MGC_DFT_LIB_ALL ( sg13g2_a21o_1__A1 , sg13g2_a21o_1__A2 , 
                         sg13g2_a21o_1__B1 , sg13g2_a21o_1__X , 
                         sg13g2_a21o_2__A1 , sg13g2_a21o_2__A2 , 
                         sg13g2_a21o_2__B1 , sg13g2_a21o_2__X , 
                         sg13g2_a21oi_1__A1 , sg13g2_a21oi_1__A2 , 
                         sg13g2_a21oi_1__B1 , sg13g2_a21oi_1__Y , 
                         sg13g2_a21oi_2__A1 , sg13g2_a21oi_2__A2 , 
                         sg13g2_a21oi_2__B1 , sg13g2_a21oi_2__Y , 
                         sg13g2_a221oi_1__A1 , sg13g2_a221oi_1__A2 , 
                         sg13g2_a221oi_1__B1 , sg13g2_a221oi_1__B2 , 
                         sg13g2_a221oi_1__C1 , sg13g2_a221oi_1__Y , 
                         sg13g2_a22oi_1__A1 , sg13g2_a22oi_1__A2 , 
                         sg13g2_a22oi_1__B1 , sg13g2_a22oi_1__B2 , 
                         sg13g2_a22oi_1__Y , sg13g2_and2_1__A , sg13g2_and2_1__B , 
                         sg13g2_and2_1__X , sg13g2_and2_2__A , sg13g2_and2_2__B , 
                         sg13g2_and2_2__X , sg13g2_and3_1__A , sg13g2_and3_1__B , 
                         sg13g2_and3_1__C , sg13g2_and3_1__X , sg13g2_and3_2__A , 
                         sg13g2_and3_2__B , sg13g2_and3_2__C , sg13g2_and3_2__X , 
                         sg13g2_and4_1__A , sg13g2_and4_1__B , sg13g2_and4_1__C , 
                         sg13g2_and4_1__D , sg13g2_and4_1__X , sg13g2_and4_2__A , 
                         sg13g2_and4_2__B , sg13g2_and4_2__C , sg13g2_and4_2__D , 
                         sg13g2_and4_2__X , sg13g2_antennanp__A , 
                         sg13g2_buf_1__A , sg13g2_buf_1__X , sg13g2_buf_16__A , 
                         sg13g2_buf_16__X , sg13g2_buf_2__A , sg13g2_buf_2__X , 
                         sg13g2_buf_4__A , sg13g2_buf_4__X , sg13g2_buf_8__A , 
                         sg13g2_buf_8__X , sg13g2_dfrbp_1__CLK , 
                         sg13g2_dfrbp_1__D , sg13g2_dfrbp_1__Q , 
                         sg13g2_dfrbp_1__Q_N , sg13g2_dfrbp_1__RESET_B , 
                         sg13g2_dfrbp_2__CLK , sg13g2_dfrbp_2__D , 
                         sg13g2_dfrbp_2__Q , sg13g2_dfrbp_2__Q_N , 
                         sg13g2_dfrbp_2__RESET_B , sg13g2_dfrbpq_1__CLK , 
                         sg13g2_dfrbpq_1__D , sg13g2_dfrbpq_1__Q , 
                         sg13g2_dfrbpq_1__RESET_B , sg13g2_dfrbpq_2__CLK , 
                         sg13g2_dfrbpq_2__D , sg13g2_dfrbpq_2__Q , 
                         sg13g2_dfrbpq_2__RESET_B , sg13g2_dlhq_1__D , 
                         sg13g2_dlhq_1__GATE , sg13g2_dlhq_1__Q , 
                         sg13g2_dlhr_1__D , sg13g2_dlhr_1__GATE , 
                         sg13g2_dlhr_1__Q , sg13g2_dlhr_1__Q_N , 
                         sg13g2_dlhr_1__RESET_B , sg13g2_dlhrq_1__D , 
                         sg13g2_dlhrq_1__GATE , sg13g2_dlhrq_1__Q , 
                         sg13g2_dlhrq_1__RESET_B , sg13g2_dllr_1__D , 
                         sg13g2_dllr_1__GATE_N , sg13g2_dllr_1__Q , 
                         sg13g2_dllr_1__Q_N , sg13g2_dllr_1__RESET_B , 
                         sg13g2_dllrq_1__D , sg13g2_dllrq_1__GATE_N , 
                         sg13g2_dllrq_1__Q , sg13g2_dllrq_1__RESET_B , 
                         sg13g2_dlygate4sd1_1__A , sg13g2_dlygate4sd1_1__X , 
                         sg13g2_dlygate4sd2_1__A , sg13g2_dlygate4sd2_1__X , 
                         sg13g2_dlygate4sd3_1__A , sg13g2_dlygate4sd3_1__X , 
                         sg13g2_ebufn_2__A , sg13g2_ebufn_2__TE_B , 
                         sg13g2_ebufn_2__Z , sg13g2_ebufn_4__A , 
                         sg13g2_ebufn_4__TE_B , sg13g2_ebufn_4__Z , 
                         sg13g2_ebufn_8__A , sg13g2_ebufn_8__TE_B , 
                         sg13g2_ebufn_8__Z , sg13g2_einvn_2__A , 
                         sg13g2_einvn_2__TE_B , sg13g2_einvn_2__Z , 
                         sg13g2_einvn_4__A , sg13g2_einvn_4__TE_B , 
                         sg13g2_einvn_4__Z , sg13g2_einvn_8__A , 
                         sg13g2_einvn_8__TE_B , sg13g2_einvn_8__Z , 
                         sg13g2_inv_1__A , sg13g2_inv_1__Y , sg13g2_inv_16__A , 
                         sg13g2_inv_16__Y , sg13g2_inv_2__A , sg13g2_inv_2__Y , 
                         sg13g2_inv_4__A , sg13g2_inv_4__Y , sg13g2_inv_8__A , 
                         sg13g2_inv_8__Y , sg13g2_lgcp_1_$_int_GATE__CLK , 
                         sg13g2_lgcp_1_$_int_GATE__GATE , 
                         sg13g2_lgcp_1_$_int_GATE__int_GATE , sg13g2_lgcp_1__CLK , 
                         sg13g2_lgcp_1__GATE , sg13g2_lgcp_1__GCLK , 
                         sg13g2_mux2_1__A0 , sg13g2_mux2_1__A1 , 
                         sg13g2_mux2_1__S , sg13g2_mux2_1__X , sg13g2_mux2_2__A0 , 
                         sg13g2_mux2_2__A1 , sg13g2_mux2_2__S , sg13g2_mux2_2__X , 
                         sg13g2_mux4_1__A0 , sg13g2_mux4_1__A1 , 
                         sg13g2_mux4_1__A2 , sg13g2_mux4_1__A3 , 
                         sg13g2_mux4_1__S0 , sg13g2_mux4_1__S1 , 
                         sg13g2_mux4_1__X , sg13g2_nand2_1__A , 
                         sg13g2_nand2_1__B , sg13g2_nand2_1__Y , 
                         sg13g2_nand2_2__A , sg13g2_nand2_2__B , 
                         sg13g2_nand2_2__Y , sg13g2_nand2b_1__A_N , 
                         sg13g2_nand2b_1__B , sg13g2_nand2b_1__Y , 
                         sg13g2_nand2b_2__A_N , sg13g2_nand2b_2__B , 
                         sg13g2_nand2b_2__Y , sg13g2_nand3_1__A , 
                         sg13g2_nand3_1__B , sg13g2_nand3_1__C , 
                         sg13g2_nand3_1__Y , sg13g2_nand3b_1__A_N , 
                         sg13g2_nand3b_1__B , sg13g2_nand3b_1__C , 
                         sg13g2_nand3b_1__Y , sg13g2_nand4_1__A , 
                         sg13g2_nand4_1__B , sg13g2_nand4_1__C , 
                         sg13g2_nand4_1__D , sg13g2_nand4_1__Y , 
                         sg13g2_nor2_1__A , sg13g2_nor2_1__B , sg13g2_nor2_1__Y , 
                         sg13g2_nor2_2__A , sg13g2_nor2_2__B , sg13g2_nor2_2__Y , 
                         sg13g2_nor2b_1__A , sg13g2_nor2b_1__B_N , 
                         sg13g2_nor2b_1__Y , sg13g2_nor2b_2__A , 
                         sg13g2_nor2b_2__B_N , sg13g2_nor2b_2__Y , 
                         sg13g2_nor3_1__A , sg13g2_nor3_1__B , sg13g2_nor3_1__C , 
                         sg13g2_nor3_1__Y , sg13g2_nor3_2__A , sg13g2_nor3_2__B , 
                         sg13g2_nor3_2__C , sg13g2_nor3_2__Y , sg13g2_nor4_1__A , 
                         sg13g2_nor4_1__B , sg13g2_nor4_1__C , sg13g2_nor4_1__D , 
                         sg13g2_nor4_1__Y , sg13g2_nor4_2__A , sg13g2_nor4_2__B , 
                         sg13g2_nor4_2__C , sg13g2_nor4_2__D , sg13g2_nor4_2__Y , 
                         sg13g2_o21ai_1__A1 , sg13g2_o21ai_1__A2 , 
                         sg13g2_o21ai_1__B1 , sg13g2_o21ai_1__Y , 
                         sg13g2_or2_1__A , sg13g2_or2_1__B , sg13g2_or2_1__X , 
                         sg13g2_or2_2__A , sg13g2_or2_2__B , sg13g2_or2_2__X , 
                         sg13g2_or3_1__A , sg13g2_or3_1__B , sg13g2_or3_1__C , 
                         sg13g2_or3_1__X , sg13g2_or3_2__A , sg13g2_or3_2__B , 
                         sg13g2_or3_2__C , sg13g2_or3_2__X , sg13g2_or4_1__A , 
                         sg13g2_or4_1__B , sg13g2_or4_1__C , sg13g2_or4_1__D , 
                         sg13g2_or4_1__X , sg13g2_or4_2__A , sg13g2_or4_2__B , 
                         sg13g2_or4_2__C , sg13g2_or4_2__D , sg13g2_or4_2__X , 
                         sg13g2_sdfbbp_1__CLK , sg13g2_sdfbbp_1__D , 
                         sg13g2_sdfbbp_1__Q , sg13g2_sdfbbp_1__Q_N , 
                         sg13g2_sdfbbp_1__RESET_B , sg13g2_sdfbbp_1__SCD , 
                         sg13g2_sdfbbp_1__SCE , sg13g2_sdfbbp_1__SET_B , 
                         sg13g2_sdfrbp_1__CLK , sg13g2_sdfrbp_1__D , 
                         sg13g2_sdfrbp_1__Q , sg13g2_sdfrbp_1__Q_N , 
                         sg13g2_sdfrbp_1__RESET_B , sg13g2_sdfrbp_1__SCD , 
                         sg13g2_sdfrbp_1__SCE , sg13g2_sdfrbp_2__CLK , 
                         sg13g2_sdfrbp_2__D , sg13g2_sdfrbp_2__Q , 
                         sg13g2_sdfrbp_2__Q_N , sg13g2_sdfrbp_2__RESET_B , 
                         sg13g2_sdfrbp_2__SCD , sg13g2_sdfrbp_2__SCE , 
                         sg13g2_sdfrbpq_1__CLK , sg13g2_sdfrbpq_1__D , 
                         sg13g2_sdfrbpq_1__Q , sg13g2_sdfrbpq_1__RESET_B , 
                         sg13g2_sdfrbpq_1__SCD , sg13g2_sdfrbpq_1__SCE , 
                         sg13g2_sdfrbpq_2__CLK , sg13g2_sdfrbpq_2__D , 
                         sg13g2_sdfrbpq_2__Q , sg13g2_sdfrbpq_2__RESET_B , 
                         sg13g2_sdfrbpq_2__SCD , sg13g2_sdfrbpq_2__SCE , 
                         sg13g2_sighold__SH , sg13g2_slgcp_1_$_int_GATE__CLK , 
                         sg13g2_slgcp_1_$_int_GATE__GATE , 
                         sg13g2_slgcp_1_$_int_GATE__SCE , 
                         sg13g2_slgcp_1_$_int_GATE__int_GATE , 
                         sg13g2_slgcp_1__CLK , sg13g2_slgcp_1__GATE , 
                         sg13g2_slgcp_1__GCLK , sg13g2_slgcp_1__SCE , 
                         sg13g2_tiehi__L_HI , sg13g2_tielo__L_LO , 
                         sg13g2_xnor2_1__A , sg13g2_xnor2_1__B , 
                         sg13g2_xnor2_1__Y , sg13g2_xor2_1__A , sg13g2_xor2_1__B , 
                         sg13g2_xor2_1__X );
input   sg13g2_a21o_1__A1 , sg13g2_a21o_1__A2 , sg13g2_a21o_1__B1 , 
        sg13g2_a21o_2__A1 , sg13g2_a21o_2__A2 , sg13g2_a21o_2__B1 , 
        sg13g2_a21oi_1__A1 , sg13g2_a21oi_1__A2 , sg13g2_a21oi_1__B1 , 
        sg13g2_a21oi_2__A1 , sg13g2_a21oi_2__A2 , sg13g2_a21oi_2__B1 , 
        sg13g2_a221oi_1__A1 , sg13g2_a221oi_1__A2 , sg13g2_a221oi_1__B1 , 
        sg13g2_a221oi_1__B2 , sg13g2_a221oi_1__C1 , sg13g2_a22oi_1__A1 , 
        sg13g2_a22oi_1__A2 , sg13g2_a22oi_1__B1 , sg13g2_a22oi_1__B2 , 
        sg13g2_and2_1__A , sg13g2_and2_1__B , sg13g2_and2_2__A , 
        sg13g2_and2_2__B , sg13g2_and3_1__A , sg13g2_and3_1__B , 
        sg13g2_and3_1__C , sg13g2_and3_2__A , sg13g2_and3_2__B , 
        sg13g2_and3_2__C , sg13g2_and4_1__A , sg13g2_and4_1__B , 
        sg13g2_and4_1__C , sg13g2_and4_1__D , sg13g2_and4_2__A , 
        sg13g2_and4_2__B , sg13g2_and4_2__C , sg13g2_and4_2__D , 
        sg13g2_antennanp__A , sg13g2_buf_1__A , sg13g2_buf_16__A , 
        sg13g2_buf_2__A , sg13g2_buf_4__A , sg13g2_buf_8__A , 
        sg13g2_dfrbp_1__CLK , sg13g2_dfrbp_1__D , sg13g2_dfrbp_1__RESET_B , 
        sg13g2_dfrbp_2__CLK , sg13g2_dfrbp_2__D , sg13g2_dfrbp_2__RESET_B , 
        sg13g2_dfrbpq_1__CLK , sg13g2_dfrbpq_1__D , sg13g2_dfrbpq_1__RESET_B , 
        sg13g2_dfrbpq_2__CLK , sg13g2_dfrbpq_2__D , sg13g2_dfrbpq_2__RESET_B , 
        sg13g2_dlhq_1__D , sg13g2_dlhq_1__GATE , sg13g2_dlhr_1__D , 
        sg13g2_dlhr_1__GATE , sg13g2_dlhr_1__RESET_B , sg13g2_dlhrq_1__D , 
        sg13g2_dlhrq_1__GATE , sg13g2_dlhrq_1__RESET_B , sg13g2_dllr_1__D , 
        sg13g2_dllr_1__GATE_N , sg13g2_dllr_1__RESET_B , sg13g2_dllrq_1__D , 
        sg13g2_dllrq_1__GATE_N , sg13g2_dllrq_1__RESET_B , 
        sg13g2_dlygate4sd1_1__A , sg13g2_dlygate4sd2_1__A , 
        sg13g2_dlygate4sd3_1__A , sg13g2_ebufn_2__A , sg13g2_ebufn_2__TE_B , 
        sg13g2_ebufn_4__A , sg13g2_ebufn_4__TE_B , sg13g2_ebufn_8__A , 
        sg13g2_ebufn_8__TE_B , sg13g2_einvn_2__A , sg13g2_einvn_2__TE_B , 
        sg13g2_einvn_4__A , sg13g2_einvn_4__TE_B , sg13g2_einvn_8__A , 
        sg13g2_einvn_8__TE_B , sg13g2_inv_1__A , sg13g2_inv_16__A , 
        sg13g2_inv_2__A , sg13g2_inv_4__A , sg13g2_inv_8__A , 
        sg13g2_lgcp_1_$_int_GATE__CLK , sg13g2_lgcp_1_$_int_GATE__GATE , 
        sg13g2_lgcp_1__CLK , sg13g2_lgcp_1__GATE , sg13g2_mux2_1__A0 , 
        sg13g2_mux2_1__A1 , sg13g2_mux2_1__S , sg13g2_mux2_2__A0 , 
        sg13g2_mux2_2__A1 , sg13g2_mux2_2__S , sg13g2_mux4_1__A0 , 
        sg13g2_mux4_1__A1 , sg13g2_mux4_1__A2 , sg13g2_mux4_1__A3 , 
        sg13g2_mux4_1__S0 , sg13g2_mux4_1__S1 , sg13g2_nand2_1__A , 
        sg13g2_nand2_1__B , sg13g2_nand2_2__A , sg13g2_nand2_2__B , 
        sg13g2_nand2b_1__A_N , sg13g2_nand2b_1__B , sg13g2_nand2b_2__A_N , 
        sg13g2_nand2b_2__B , sg13g2_nand3_1__A , sg13g2_nand3_1__B , 
        sg13g2_nand3_1__C , sg13g2_nand3b_1__A_N , sg13g2_nand3b_1__B , 
        sg13g2_nand3b_1__C , sg13g2_nand4_1__A , sg13g2_nand4_1__B , 
        sg13g2_nand4_1__C , sg13g2_nand4_1__D , sg13g2_nor2_1__A , 
        sg13g2_nor2_1__B , sg13g2_nor2_2__A , sg13g2_nor2_2__B , 
        sg13g2_nor2b_1__A , sg13g2_nor2b_1__B_N , sg13g2_nor2b_2__A , 
        sg13g2_nor2b_2__B_N , sg13g2_nor3_1__A , sg13g2_nor3_1__B , 
        sg13g2_nor3_1__C , sg13g2_nor3_2__A , sg13g2_nor3_2__B , 
        sg13g2_nor3_2__C , sg13g2_nor4_1__A , sg13g2_nor4_1__B , 
        sg13g2_nor4_1__C , sg13g2_nor4_1__D , sg13g2_nor4_2__A , 
        sg13g2_nor4_2__B , sg13g2_nor4_2__C , sg13g2_nor4_2__D , 
        sg13g2_o21ai_1__A1 , sg13g2_o21ai_1__A2 , sg13g2_o21ai_1__B1 , 
        sg13g2_or2_1__A , sg13g2_or2_1__B , sg13g2_or2_2__A , sg13g2_or2_2__B , 
        sg13g2_or3_1__A , sg13g2_or3_1__B , sg13g2_or3_1__C , sg13g2_or3_2__A , 
        sg13g2_or3_2__B , sg13g2_or3_2__C , sg13g2_or4_1__A , sg13g2_or4_1__B , 
        sg13g2_or4_1__C , sg13g2_or4_1__D , sg13g2_or4_2__A , sg13g2_or4_2__B , 
        sg13g2_or4_2__C , sg13g2_or4_2__D , sg13g2_sdfbbp_1__CLK , 
        sg13g2_sdfbbp_1__D , sg13g2_sdfbbp_1__RESET_B , sg13g2_sdfbbp_1__SCD , 
        sg13g2_sdfbbp_1__SCE , sg13g2_sdfbbp_1__SET_B , sg13g2_sdfrbp_1__CLK , 
        sg13g2_sdfrbp_1__D , sg13g2_sdfrbp_1__RESET_B , sg13g2_sdfrbp_1__SCD , 
        sg13g2_sdfrbp_1__SCE , sg13g2_sdfrbp_2__CLK , sg13g2_sdfrbp_2__D , 
        sg13g2_sdfrbp_2__RESET_B , sg13g2_sdfrbp_2__SCD , sg13g2_sdfrbp_2__SCE , 
        sg13g2_sdfrbpq_1__CLK , sg13g2_sdfrbpq_1__D , sg13g2_sdfrbpq_1__RESET_B , 
        sg13g2_sdfrbpq_1__SCD , sg13g2_sdfrbpq_1__SCE , sg13g2_sdfrbpq_2__CLK , 
        sg13g2_sdfrbpq_2__D , sg13g2_sdfrbpq_2__RESET_B , sg13g2_sdfrbpq_2__SCD , 
        sg13g2_sdfrbpq_2__SCE , sg13g2_slgcp_1_$_int_GATE__CLK , 
        sg13g2_slgcp_1_$_int_GATE__GATE , sg13g2_slgcp_1_$_int_GATE__SCE , 
        sg13g2_slgcp_1__CLK , sg13g2_slgcp_1__GATE , sg13g2_slgcp_1__SCE , 
        sg13g2_xnor2_1__A , sg13g2_xnor2_1__B , sg13g2_xor2_1__A , 
        sg13g2_xor2_1__B ;
output  sg13g2_a21o_1__X , sg13g2_a21o_2__X , sg13g2_a21oi_1__Y , 
        sg13g2_a21oi_2__Y , sg13g2_a221oi_1__Y , sg13g2_a22oi_1__Y , 
        sg13g2_and2_1__X , sg13g2_and2_2__X , sg13g2_and3_1__X , 
        sg13g2_and3_2__X , sg13g2_and4_1__X , sg13g2_and4_2__X , sg13g2_buf_1__X , 
        sg13g2_buf_16__X , sg13g2_buf_2__X , sg13g2_buf_4__X , sg13g2_buf_8__X , 
        sg13g2_dfrbp_1__Q , sg13g2_dfrbp_1__Q_N , sg13g2_dfrbp_2__Q , 
        sg13g2_dfrbp_2__Q_N , sg13g2_dfrbpq_1__Q , sg13g2_dfrbpq_2__Q , 
        sg13g2_dlhq_1__Q , sg13g2_dlhr_1__Q , sg13g2_dlhr_1__Q_N , 
        sg13g2_dlhrq_1__Q , sg13g2_dllr_1__Q , sg13g2_dllr_1__Q_N , 
        sg13g2_dllrq_1__Q , sg13g2_dlygate4sd1_1__X , sg13g2_dlygate4sd2_1__X , 
        sg13g2_dlygate4sd3_1__X , sg13g2_ebufn_2__Z , sg13g2_ebufn_4__Z , 
        sg13g2_ebufn_8__Z , sg13g2_einvn_2__Z , sg13g2_einvn_4__Z , 
        sg13g2_einvn_8__Z , sg13g2_inv_1__Y , sg13g2_inv_16__Y , sg13g2_inv_2__Y , 
        sg13g2_inv_4__Y , sg13g2_inv_8__Y , sg13g2_lgcp_1_$_int_GATE__int_GATE , 
        sg13g2_lgcp_1__GCLK , sg13g2_mux2_1__X , sg13g2_mux2_2__X , 
        sg13g2_mux4_1__X , sg13g2_nand2_1__Y , sg13g2_nand2_2__Y , 
        sg13g2_nand2b_1__Y , sg13g2_nand2b_2__Y , sg13g2_nand3_1__Y , 
        sg13g2_nand3b_1__Y , sg13g2_nand4_1__Y , sg13g2_nor2_1__Y , 
        sg13g2_nor2_2__Y , sg13g2_nor2b_1__Y , sg13g2_nor2b_2__Y , 
        sg13g2_nor3_1__Y , sg13g2_nor3_2__Y , sg13g2_nor4_1__Y , 
        sg13g2_nor4_2__Y , sg13g2_o21ai_1__Y , sg13g2_or2_1__X , sg13g2_or2_2__X , 
        sg13g2_or3_1__X , sg13g2_or3_2__X , sg13g2_or4_1__X , sg13g2_or4_2__X , 
        sg13g2_sdfbbp_1__Q , sg13g2_sdfbbp_1__Q_N , sg13g2_sdfrbp_1__Q , 
        sg13g2_sdfrbp_1__Q_N , sg13g2_sdfrbp_2__Q , sg13g2_sdfrbp_2__Q_N , 
        sg13g2_sdfrbpq_1__Q , sg13g2_sdfrbpq_2__Q , 
        sg13g2_slgcp_1_$_int_GATE__int_GATE , sg13g2_slgcp_1__GCLK , 
        sg13g2_tiehi__L_HI , sg13g2_tielo__L_LO , sg13g2_xnor2_1__Y , 
        sg13g2_xor2_1__X ;
inout  sg13g2_sighold__SH ;

  sg13g2_a21o_1  sg13g2_a21o_1 (sg13g2_a21o_1__A1 , sg13g2_a21o_1__A2 , 
               sg13g2_a21o_1__B1 , sg13g2_a21o_1__X);
  sg13g2_a21o_2  sg13g2_a21o_2 (sg13g2_a21o_2__A1 , sg13g2_a21o_2__A2 , 
               sg13g2_a21o_2__B1 , sg13g2_a21o_2__X);
  sg13g2_a21oi_1  sg13g2_a21oi_1 (sg13g2_a21oi_1__A1 , sg13g2_a21oi_1__A2 , 
                sg13g2_a21oi_1__B1 , sg13g2_a21oi_1__Y);
  sg13g2_a21oi_2  sg13g2_a21oi_2 (sg13g2_a21oi_2__A1 , sg13g2_a21oi_2__A2 , 
                sg13g2_a21oi_2__B1 , sg13g2_a21oi_2__Y);
  sg13g2_a221oi_1  sg13g2_a221oi_1 (sg13g2_a221oi_1__A1 , sg13g2_a221oi_1__A2 , 
                 sg13g2_a221oi_1__B1 , sg13g2_a221oi_1__B2 , sg13g2_a221oi_1__C1 , 
                 sg13g2_a221oi_1__Y);
  sg13g2_a22oi_1  sg13g2_a22oi_1 (sg13g2_a22oi_1__A1 , sg13g2_a22oi_1__A2 , 
                sg13g2_a22oi_1__B1 , sg13g2_a22oi_1__B2 , sg13g2_a22oi_1__Y);
  sg13g2_and2_1  sg13g2_and2_1 (sg13g2_and2_1__A , sg13g2_and2_1__B , 
               sg13g2_and2_1__X);
  sg13g2_and2_2  sg13g2_and2_2 (sg13g2_and2_2__A , sg13g2_and2_2__B , 
               sg13g2_and2_2__X);
  sg13g2_and3_1  sg13g2_and3_1 (sg13g2_and3_1__A , sg13g2_and3_1__B , 
               sg13g2_and3_1__C , sg13g2_and3_1__X);
  sg13g2_and3_2  sg13g2_and3_2 (sg13g2_and3_2__A , sg13g2_and3_2__B , 
               sg13g2_and3_2__C , sg13g2_and3_2__X);
  sg13g2_and4_1  sg13g2_and4_1 (sg13g2_and4_1__A , sg13g2_and4_1__B , 
               sg13g2_and4_1__C , sg13g2_and4_1__D , sg13g2_and4_1__X);
  sg13g2_and4_2  sg13g2_and4_2 (sg13g2_and4_2__A , sg13g2_and4_2__B , 
               sg13g2_and4_2__C , sg13g2_and4_2__D , sg13g2_and4_2__X);
  sg13g2_antennanp  sg13g2_antennanp (sg13g2_antennanp__A);
  sg13g2_buf_1  sg13g2_buf_1 (sg13g2_buf_1__A , sg13g2_buf_1__X);
  sg13g2_buf_16  sg13g2_buf_16 (sg13g2_buf_16__A , sg13g2_buf_16__X);
  sg13g2_buf_2  sg13g2_buf_2 (sg13g2_buf_2__A , sg13g2_buf_2__X);
  sg13g2_buf_4  sg13g2_buf_4 (sg13g2_buf_4__A , sg13g2_buf_4__X);
  sg13g2_buf_8  sg13g2_buf_8 (sg13g2_buf_8__A , sg13g2_buf_8__X);
  sg13g2_decap_4  sg13g2_decap_4 ();
  sg13g2_decap_8  sg13g2_decap_8 ();
  sg13g2_dfrbp_1  sg13g2_dfrbp_1 (sg13g2_dfrbp_1__CLK , sg13g2_dfrbp_1__D , 
                sg13g2_dfrbp_1__Q , sg13g2_dfrbp_1__Q_N , 
                sg13g2_dfrbp_1__RESET_B);
  sg13g2_dfrbp_2  sg13g2_dfrbp_2 (sg13g2_dfrbp_2__CLK , sg13g2_dfrbp_2__D , 
                sg13g2_dfrbp_2__Q , sg13g2_dfrbp_2__Q_N , 
                sg13g2_dfrbp_2__RESET_B);
  sg13g2_dfrbpq_1  sg13g2_dfrbpq_1 (sg13g2_dfrbpq_1__CLK , sg13g2_dfrbpq_1__D , 
                 sg13g2_dfrbpq_1__Q , sg13g2_dfrbpq_1__RESET_B);
  sg13g2_dfrbpq_2  sg13g2_dfrbpq_2 (sg13g2_dfrbpq_2__CLK , sg13g2_dfrbpq_2__D , 
                 sg13g2_dfrbpq_2__Q , sg13g2_dfrbpq_2__RESET_B);
  sg13g2_dlhq_1  sg13g2_dlhq_1 (sg13g2_dlhq_1__D , sg13g2_dlhq_1__GATE , 
               sg13g2_dlhq_1__Q);
  sg13g2_dlhr_1  sg13g2_dlhr_1 (sg13g2_dlhr_1__D , sg13g2_dlhr_1__GATE , 
               sg13g2_dlhr_1__Q , sg13g2_dlhr_1__Q_N , sg13g2_dlhr_1__RESET_B);
  sg13g2_dlhrq_1  sg13g2_dlhrq_1 (sg13g2_dlhrq_1__D , sg13g2_dlhrq_1__GATE , 
                sg13g2_dlhrq_1__Q , sg13g2_dlhrq_1__RESET_B);
  sg13g2_dllr_1  sg13g2_dllr_1 (sg13g2_dllr_1__D , sg13g2_dllr_1__GATE_N , 
               sg13g2_dllr_1__Q , sg13g2_dllr_1__Q_N , sg13g2_dllr_1__RESET_B);
  sg13g2_dllrq_1  sg13g2_dllrq_1 (sg13g2_dllrq_1__D , sg13g2_dllrq_1__GATE_N , 
                sg13g2_dllrq_1__Q , sg13g2_dllrq_1__RESET_B);
  sg13g2_dlygate4sd1_1  sg13g2_dlygate4sd1_1 (sg13g2_dlygate4sd1_1__A , 
                      sg13g2_dlygate4sd1_1__X);
  sg13g2_dlygate4sd2_1  sg13g2_dlygate4sd2_1 (sg13g2_dlygate4sd2_1__A , 
                      sg13g2_dlygate4sd2_1__X);
  sg13g2_dlygate4sd3_1  sg13g2_dlygate4sd3_1 (sg13g2_dlygate4sd3_1__A , 
                      sg13g2_dlygate4sd3_1__X);
  sg13g2_ebufn_2  sg13g2_ebufn_2 (sg13g2_ebufn_2__A , sg13g2_ebufn_2__TE_B , 
                sg13g2_ebufn_2__Z);
  sg13g2_ebufn_4  sg13g2_ebufn_4 (sg13g2_ebufn_4__A , sg13g2_ebufn_4__TE_B , 
                sg13g2_ebufn_4__Z);
  sg13g2_ebufn_8  sg13g2_ebufn_8 (sg13g2_ebufn_8__A , sg13g2_ebufn_8__TE_B , 
                sg13g2_ebufn_8__Z);
  sg13g2_einvn_2  sg13g2_einvn_2 (sg13g2_einvn_2__A , sg13g2_einvn_2__TE_B , 
                sg13g2_einvn_2__Z);
  sg13g2_einvn_4  sg13g2_einvn_4 (sg13g2_einvn_4__A , sg13g2_einvn_4__TE_B , 
                sg13g2_einvn_4__Z);
  sg13g2_einvn_8  sg13g2_einvn_8 (sg13g2_einvn_8__A , sg13g2_einvn_8__TE_B , 
                sg13g2_einvn_8__Z);
  sg13g2_fill_1  sg13g2_fill_1 ();
  sg13g2_fill_2  sg13g2_fill_2 ();
  sg13g2_fill_4  sg13g2_fill_4 ();
  sg13g2_fill_8  sg13g2_fill_8 ();
  sg13g2_inv_1  sg13g2_inv_1 (sg13g2_inv_1__A , sg13g2_inv_1__Y);
  sg13g2_inv_16  sg13g2_inv_16 (sg13g2_inv_16__A , sg13g2_inv_16__Y);
  sg13g2_inv_2  sg13g2_inv_2 (sg13g2_inv_2__A , sg13g2_inv_2__Y);
  sg13g2_inv_4  sg13g2_inv_4 (sg13g2_inv_4__A , sg13g2_inv_4__Y);
  sg13g2_inv_8  sg13g2_inv_8 (sg13g2_inv_8__A , sg13g2_inv_8__Y);
  sg13g2_lgcp_1_$_int_GATE  sg13g2_lgcp_1_$_int_GATE (
                          sg13g2_lgcp_1_$_int_GATE__CLK , 
                          sg13g2_lgcp_1_$_int_GATE__GATE , 
                          sg13g2_lgcp_1_$_int_GATE__int_GATE);
  sg13g2_lgcp_1  sg13g2_lgcp_1 (sg13g2_lgcp_1__CLK , sg13g2_lgcp_1__GATE , 
               sg13g2_lgcp_1__GCLK);
  sg13g2_mux2_1  sg13g2_mux2_1 (sg13g2_mux2_1__A0 , sg13g2_mux2_1__A1 , 
               sg13g2_mux2_1__S , sg13g2_mux2_1__X);
  sg13g2_mux2_2  sg13g2_mux2_2 (sg13g2_mux2_2__A0 , sg13g2_mux2_2__A1 , 
               sg13g2_mux2_2__S , sg13g2_mux2_2__X);
  sg13g2_mux4_1  sg13g2_mux4_1 (sg13g2_mux4_1__A0 , sg13g2_mux4_1__A1 , 
               sg13g2_mux4_1__A2 , sg13g2_mux4_1__A3 , sg13g2_mux4_1__S0 , 
               sg13g2_mux4_1__S1 , sg13g2_mux4_1__X);
  sg13g2_nand2_1  sg13g2_nand2_1 (sg13g2_nand2_1__A , sg13g2_nand2_1__B , 
                sg13g2_nand2_1__Y);
  sg13g2_nand2_2  sg13g2_nand2_2 (sg13g2_nand2_2__A , sg13g2_nand2_2__B , 
                sg13g2_nand2_2__Y);
  sg13g2_nand2b_1  sg13g2_nand2b_1 (sg13g2_nand2b_1__A_N , sg13g2_nand2b_1__B , 
                 sg13g2_nand2b_1__Y);
  sg13g2_nand2b_2  sg13g2_nand2b_2 (sg13g2_nand2b_2__A_N , sg13g2_nand2b_2__B , 
                 sg13g2_nand2b_2__Y);
  sg13g2_nand3_1  sg13g2_nand3_1 (sg13g2_nand3_1__A , sg13g2_nand3_1__B , 
                sg13g2_nand3_1__C , sg13g2_nand3_1__Y);
  sg13g2_nand3b_1  sg13g2_nand3b_1 (sg13g2_nand3b_1__A_N , sg13g2_nand3b_1__B , 
                 sg13g2_nand3b_1__C , sg13g2_nand3b_1__Y);
  sg13g2_nand4_1  sg13g2_nand4_1 (sg13g2_nand4_1__A , sg13g2_nand4_1__B , 
                sg13g2_nand4_1__C , sg13g2_nand4_1__D , sg13g2_nand4_1__Y);
  sg13g2_nor2_1  sg13g2_nor2_1 (sg13g2_nor2_1__A , sg13g2_nor2_1__B , 
               sg13g2_nor2_1__Y);
  sg13g2_nor2_2  sg13g2_nor2_2 (sg13g2_nor2_2__A , sg13g2_nor2_2__B , 
               sg13g2_nor2_2__Y);
  sg13g2_nor2b_1  sg13g2_nor2b_1 (sg13g2_nor2b_1__A , sg13g2_nor2b_1__B_N , 
                sg13g2_nor2b_1__Y);
  sg13g2_nor2b_2  sg13g2_nor2b_2 (sg13g2_nor2b_2__A , sg13g2_nor2b_2__B_N , 
                sg13g2_nor2b_2__Y);
  sg13g2_nor3_1  sg13g2_nor3_1 (sg13g2_nor3_1__A , sg13g2_nor3_1__B , 
               sg13g2_nor3_1__C , sg13g2_nor3_1__Y);
  sg13g2_nor3_2  sg13g2_nor3_2 (sg13g2_nor3_2__A , sg13g2_nor3_2__B , 
               sg13g2_nor3_2__C , sg13g2_nor3_2__Y);
  sg13g2_nor4_1  sg13g2_nor4_1 (sg13g2_nor4_1__A , sg13g2_nor4_1__B , 
               sg13g2_nor4_1__C , sg13g2_nor4_1__D , sg13g2_nor4_1__Y);
  sg13g2_nor4_2  sg13g2_nor4_2 (sg13g2_nor4_2__A , sg13g2_nor4_2__B , 
               sg13g2_nor4_2__C , sg13g2_nor4_2__D , sg13g2_nor4_2__Y);
  sg13g2_o21ai_1  sg13g2_o21ai_1 (sg13g2_o21ai_1__A1 , sg13g2_o21ai_1__A2 , 
                sg13g2_o21ai_1__B1 , sg13g2_o21ai_1__Y);
  sg13g2_or2_1  sg13g2_or2_1 (sg13g2_or2_1__A , sg13g2_or2_1__B , 
              sg13g2_or2_1__X);
  sg13g2_or2_2  sg13g2_or2_2 (sg13g2_or2_2__A , sg13g2_or2_2__B , 
              sg13g2_or2_2__X);
  sg13g2_or3_1  sg13g2_or3_1 (sg13g2_or3_1__A , sg13g2_or3_1__B , 
              sg13g2_or3_1__C , sg13g2_or3_1__X);
  sg13g2_or3_2  sg13g2_or3_2 (sg13g2_or3_2__A , sg13g2_or3_2__B , 
              sg13g2_or3_2__C , sg13g2_or3_2__X);
  sg13g2_or4_1  sg13g2_or4_1 (sg13g2_or4_1__A , sg13g2_or4_1__B , 
              sg13g2_or4_1__C , sg13g2_or4_1__D , sg13g2_or4_1__X);
  sg13g2_or4_2  sg13g2_or4_2 (sg13g2_or4_2__A , sg13g2_or4_2__B , 
              sg13g2_or4_2__C , sg13g2_or4_2__D , sg13g2_or4_2__X);
  sg13g2_sdfbbp_1  sg13g2_sdfbbp_1 (sg13g2_sdfbbp_1__CLK , sg13g2_sdfbbp_1__D , 
                 sg13g2_sdfbbp_1__Q , sg13g2_sdfbbp_1__Q_N , 
                 sg13g2_sdfbbp_1__RESET_B , sg13g2_sdfbbp_1__SCD , 
                 sg13g2_sdfbbp_1__SCE , sg13g2_sdfbbp_1__SET_B);
  sg13g2_sdfrbp_1  sg13g2_sdfrbp_1 (sg13g2_sdfrbp_1__CLK , sg13g2_sdfrbp_1__D , 
                 sg13g2_sdfrbp_1__Q , sg13g2_sdfrbp_1__Q_N , 
                 sg13g2_sdfrbp_1__RESET_B , sg13g2_sdfrbp_1__SCD , 
                 sg13g2_sdfrbp_1__SCE);
  sg13g2_sdfrbp_2  sg13g2_sdfrbp_2 (sg13g2_sdfrbp_2__CLK , sg13g2_sdfrbp_2__D , 
                 sg13g2_sdfrbp_2__Q , sg13g2_sdfrbp_2__Q_N , 
                 sg13g2_sdfrbp_2__RESET_B , sg13g2_sdfrbp_2__SCD , 
                 sg13g2_sdfrbp_2__SCE);
  sg13g2_sdfrbpq_1  sg13g2_sdfrbpq_1 (sg13g2_sdfrbpq_1__CLK , 
                  sg13g2_sdfrbpq_1__D , sg13g2_sdfrbpq_1__Q , 
                  sg13g2_sdfrbpq_1__RESET_B , sg13g2_sdfrbpq_1__SCD , 
                  sg13g2_sdfrbpq_1__SCE);
  sg13g2_sdfrbpq_2  sg13g2_sdfrbpq_2 (sg13g2_sdfrbpq_2__CLK , 
                  sg13g2_sdfrbpq_2__D , sg13g2_sdfrbpq_2__Q , 
                  sg13g2_sdfrbpq_2__RESET_B , sg13g2_sdfrbpq_2__SCD , 
                  sg13g2_sdfrbpq_2__SCE);
  sg13g2_sighold  sg13g2_sighold (sg13g2_sighold__SH);
  sg13g2_slgcp_1_$_int_GATE  sg13g2_slgcp_1_$_int_GATE (
                           sg13g2_slgcp_1_$_int_GATE__CLK , 
                           sg13g2_slgcp_1_$_int_GATE__GATE , 
                           sg13g2_slgcp_1_$_int_GATE__SCE , 
                           sg13g2_slgcp_1_$_int_GATE__int_GATE);
  sg13g2_slgcp_1  sg13g2_slgcp_1 (sg13g2_slgcp_1__CLK , sg13g2_slgcp_1__GATE , 
                sg13g2_slgcp_1__GCLK , sg13g2_slgcp_1__SCE);
  sg13g2_tiehi  sg13g2_tiehi (sg13g2_tiehi__L_HI);
  sg13g2_tielo  sg13g2_tielo (sg13g2_tielo__L_LO);
  sg13g2_xnor2_1  sg13g2_xnor2_1 (sg13g2_xnor2_1__A , sg13g2_xnor2_1__B , 
                sg13g2_xnor2_1__Y);
  sg13g2_xor2_1  sg13g2_xor2_1 (sg13g2_xor2_1__A , sg13g2_xor2_1__B , 
               sg13g2_xor2_1__X);
endmodule

