/* Generated by Tessent Shell 2022.3 at Sat Nov 15 20:33:09 EST 2025 */
module memlibc_memory_bist_assembly(BIST_CLK, m1_A_DLY, m1_A_DIN, m1_A_ADDR, m1_A_MEN, 
                                    m1_A_WEN, m1_A_REN, m1_A_DOUT);
  input  [31:0] m1_A_DIN;
  input  [12:0] m1_A_ADDR;
  input  BIST_CLK, m1_A_DLY, m1_A_MEN, m1_A_WEN, m1_A_REN;
  output [31:0] m1_A_DOUT;

  memlibc_memory_bist_assembly_mem_container mem_container_inst(
      .BIST_CLK(BIST_CLK), .m1_A_DLY(m1_A_DLY), .m1_A_DIN(m1_A_DIN), .m1_A_ADDR(m1_A_ADDR), 
      .m1_A_MEN(m1_A_MEN), .m1_A_WEN(m1_A_WEN), .m1_A_REN(m1_A_REN), .A_DOUT(m1_A_DOUT)
  );
endmodule

module memlibc_memory_bist_assembly_mem_container(BIST_CLK, m1_A_DLY, m1_A_DIN, 
                                                  m1_A_ADDR, m1_A_MEN, m1_A_WEN, 
                                                  m1_A_REN, A_DOUT);
  input  [31:0] m1_A_DIN;
  input  [12:0] m1_A_ADDR;
  input  BIST_CLK, m1_A_DLY, m1_A_MEN, m1_A_WEN, m1_A_REN;
  output [31:0] A_DOUT;

  RM_IHPSG13_1P_8192x32_c4 m1_mem_inst(
      .A_CLK(BIST_CLK), .A_MEN(m1_A_MEN), .A_WEN(m1_A_WEN), .A_REN(m1_A_REN), .A_ADDR(m1_A_ADDR), 
      .A_DIN(m1_A_DIN), .A_DLY(m1_A_DLY), .A_DOUT(A_DOUT)
  );
endmodule

