#! /bin/sh -f
#\
mkdir -p logfiles
#\
mkdir -p patterns
#\
exec tessent -shell -log logfiles/$0.log -replace -dofile "$0"

set PDK_ROOT ../../tech
set design_name croc_chip 
# Set the context
set_context pattern -scan -design_id gate2

# Set the location of the TSDB. Default is the current working directory.
set_tsdb_output_directory ../tsdb_outdir
# Read the cell library 
# Read the cell library
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_stdcell.tcelllib
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_io.tcelllib
read_cell_library ${PDK_ROOT}/tessent/memories/RM_IHPSG13_1P_256x64_c2_bm_bist.atpglib

read_design ${design_name} -design_id gate2
#add_black_boxes -modules { \
#                    RM_IHPSG13_1P_256x64_c2_bm_bist \
#             }

set_current_design ${design_name} 

# setting the test mode to lbist whichis the default
# this mode is used for pattern retargetting
set_current_mode lbist
import_scan_mode edt_mode 
report_scan_modes
# set_static_dft_signal_values int_ltest_en 1
#set_static_dft_signal_values all_test 1
#set_static_dft_signal_values tck_occ_en 1

# there are 3 types of instruments needed for this fault simulation
#    EDT for PRPG/COMPACTOR/MISR configuration and chain tracing
#    LBIST for the controls and chian tracing
#    OCC for clocks
# both the EDT and OCCs will be loaded with the imported scan mode 
#add_core_instances -instance croc_chip_rtl2_tessent_lbist
#add_core_instances -instance {*_tessent_occ_*_inst croc_chip_rtl2_tessent_sib_sti_inst} -param {static_clock_control external}
add_core_instances -module *tessent_lbist
#set_lbist_controller_options -capture_procedure {clk_i_single_pulse 70 clk_i_double_pulse 20 jtag_tck_i_single_pulse 5 jtag_tck_i_double_pulse 5 bscan_occ_single_pulse 0  sti_occ_ncp 0} 


# set DFT signals 
set_static_dft_signal_values mcp_bounding_en 1
set_static_dft_signal_values memory_bypass_en 1
set_static_dft_signal_values output_pad_disable 1
set_static_dft_signal_values control_test_point_en 1
set_static_dft_signal_values observe_test_point_en 1
set_static_dft_signal_values x_bounding_en 1

set_static_dft_signal_values int_ltest_en 1
set_static_dft_signal_values ext_ltest_en 0

set_static_dft_signal_values tck_occ_en 1

#set_core_instance_parameters -instrument_type occ -parameter_values {static_clock_control external}


add_input_constraint rst_ni -C1
add_input_constraint jtag_trst_ni -C1
add_input_constraint unused2_i -c0
add_nofault [get_instance *tessent*]

set_static_dft_signal_values ltest_en 1


#set_lbist_controller_options -capture_procedure {clk_i_single_pulse 70 clk_i_double_pulse 0 jtag_tck_i_single_pulse 30 jtag_tck_i_double_pulse 0 bscan_occ_single_pulse 0  sti_occ_ncp 0} 
set_lbist_controller_options -capture_procedure { ALL 70 single_pulse 15 double_pulse 15 bscan_occ 0  sti_occ_ncp 0} 

#set_core_instance_parameters -instrument_type occ -parameter_values {static_clock_control external}

report_static_dft_signal_settings


set_system_mode analysis

report_scan_cells > scan_cells_fsim.rpt
report_clocks
report_pin_constraints

add_faults -all
set_random_patterns 1024
simulate_patterns -source bist -store_patterns all
report_statistics
# write parallel pattern verilog testbench
write_patterns patterns/${design_name}_lbist_parallel.v -verilog -parallel -replace -parameter_list {SIM_KEEP_PATH 1}
 
# Save the TCD, PatternDB, flat model, and fault list to the TSDB
write_tsdb_data -replace

report_lbist_configuration -hardware_default_compatibility

exit

